import type { FormCopy, FormData } from "./types";

export const SESSION_KEY = "gbva-appearance-request";
export const FORMSPREE_URL = "https://formspree.io/f/xpqybzjj";

/** Total number of wizard steps. Matches STEP_COMPONENTS length in AppearanceRequestForm.tsx. */
export const TOTAL_STEPS = 5;

/** Static copy for the appearance request form. */
export const FORM_COPY: FormCopy = {
  step0Title: "Event Details",
  step1Title: "Location",
  step2Title: "Event Needs",
  step3Title: "Logistics",
  step4Title: "Contact & Notes",

  navBack: "← Back",
  navNext: "Next →",
  navSubmit: "Submit Request",
  navSubmitting: "Submitting…",
  navReset: "Reset Form",
  navResetModalHeading: "Reset Form?",
  navResetModalBody:
    "This will clear all your saved information and take you back to step one. This can\u2019t be undone.",
  navResetModalConfirm: "Yes, start over",
  navResetModalCancel: "Keep my info",

  successIcon: "👻",
  successHeading: "Request Received!",
  successBody:
    "Thank you for reaching out to Ghostbusters Virginia. We\u2019ve received your appearance request and will be in touch soon. Who ya gonna call?",

  eventNameLabel: "Event Name",
  eventTypeLegend: "Event Type",
  eventTypeOptions: [
    "Birthday",
    "Car Show",
    "Charity Fundraiser",
    "Convention / Trade Show",
    "Festival",
    "Hospital / Home Visit",
    "Parade",
    "TV / Radio / Podcast",
    "Trunk or Treat",
    "Other",
  ],
  eventTypeOtherLabel: "Please describe the event type",

  isScheduledLegend: "Is the event already scheduled?",
  unscheduledNoteLabel: "Any context on timing?",
  unscheduledNotePlaceholder:
    "e.g. planning for summer, targeting a specific month, still exploring options\u2026",
  optionYes: "Yes",
  optionNo: "No",
  eventStartDateLabel: "Event Start Date",
  eventEndDateLabel: "Event End Date",
  eventStartTimeLabel: "Event Start Time",
  eventEndTimeLabel: "Event End Time",
  earliestSetupTimeLabel: "Earliest Setup / Arrival Time",
  requiredLeaveTimeLabel: "Required Leave Time",

  locationSearchLabel: "Search for a Venue or Address",
  locationSearchPlaceholder: "Start typing a place name or address\u2026",
  locationDescriptionLabel: "Location Description",
  locationDescriptionPlaceholder:
    "Describe the venue or provide any helpful location context\u2026",
  addressLine1Label: "Street Address",
  addressLine2Label: "Address Line 2",
  cityLabel: "City",
  stateLabel: "State",
  zipCodeLabel: "ZIP Code",

  requestEctoVehicleLegend: "Are you requesting an Ecto vehicle?",
  ectoVehicleParkingInfoLabel: "Where should Ecto vehicles park?",
  ectoVehicleParkingInfoPlaceholder: "Parking area, access instructions, etc.",
  maxEctoVehiclesLabel: "How many ecto vehicles?",
  maxEctoVehiclesShortLabel: "How many ecto vehicles?",
  memberParkingInfoLabel: "Where should members park on the day of the event?",
  memberParkingInfoPlaceholder: "Describe member parking location and instructions\u2026",

  tablesLegend: "Tables",
  tablesOptionWeBring: "We provide tables",
  tablesOptionGbvaBrings: "Ghostbusters Virginia provides tables",
  tablesOptionNA: "Not needed",
  numberOfTablesLabel: "How many tables will be provided?",
  numberOfTablesNeededLabel: "How many tables will you need provided?",
  chairsLegend: "Chairs",
  chairsOptionWeBring: "We provide chairs",
  chairsOptionGbvaBrings: "Ghostbusters Virginia provides chairs",
  chairsOptionNA: "Not needed",
  numberOfChairsLabel: "How many chairs will be provided?",
  numberOfChairsNeededLabel: "How many chairs will you need provided?",

  charitableDonationsLegend: "Are charitable donations allowed at this event?",
  needsLogisticsLegend: "Will you need any of the following? Chairs, tables, or Ecto vehicles?",
  requestEctoVehicleHint: "We\u2019ll ask follow-up questions in the next steps.",
  needsLogisticsHint: "We\u2019ll ask follow-up questions in the next steps.",
  errorNeedsLogisticsRequired: "Please indicate whether you need any logistics support.",
  collectDonationsForHostLegend: "For whom can we collect donations?",
  charityInfoLabel: "Which charity?",
  charityInfoPlaceholder: "Charity name or website URL\u2026",
  charityInfoHint: "Please provide the charity name or website URL.",
  optionOurChoice: "My choice of approved charity",
  optionYourChoice: "Ghostbusters, Virginia's choice of charity",
  optionUnsure: "Unsure",

  contactNameLabel: "Name",
  contactEmailLabel: "Email Address",
  contactPhoneLabel: "Phone Number",
  companyNameLabel: "Company Name",
  companyWebsiteLabel: "Company / Event Website",
  companyWebsitePlaceholder: "https://",

  additionalInfoLabel: "Is there anything else you\u2019d like us to know?",
  additionalInfoPlaceholder:
    "Any additional context, special requirements, parking restrictions, or general questions not covered here\u2026",

  errorEventNameRequired: "Event name is required.",
  errorEventTypeRequired: "Please select an event type.",
  errorEventTypeOtherRequired: "Please describe the event type.",
  errorIsScheduledRequired: "Please indicate whether the event is already scheduled.",
  errorEventStartDateRequired: "Event start date is required.",
  errorEventEndDateRequired: "Event end date is required.",
  errorEventStartTimeRequired: "Event start time is required.",
  errorEventEndTimeRequired: "Event end time is required.",
  errorEarliestSetupTimeRequired: "Earliest setup / arrival time is required.",
  errorRequiredLeaveTimeRequired: "Required leave time is required.",
  errorRequestEctoVehicleRequired: "Please indicate whether you are requesting an ecto vehicle.",
  errorEctoVehicleParkingInfoRequired: "Ecto vehicle parking information is required.",
  errorMaxEctoVehiclesRequired: "Maximum number of ecto vehicles is required.",
  errorMemberParkingInfoRequired: "Member parking information is required.",
  errorTablesRequired: "Please indicate table availability.",
  errorChairsRequired: "Please indicate chair availability.",
  errorNumberOfTablesRequired: "Please specify the number of tables.",
  errorNumberOfChairsRequired: "Please specify the number of chairs.",
  errorCharitableDonationsRequired: "Please indicate whether charitable donations are allowed.",
  errorAddressLine1Required: "Street address is required.",
  errorCityRequired: "City is required.",
  errorStateRequired: "State is required.",
  errorContactNameRequired: "Name is required.",
  errorContactEmailRequired: "Email address is required.",
  errorContactEmailInvalid: "Please enter a valid email address.",
  errorSubmitFailed: "Submission failed. Please try again.",
  errorNetworkError: "A network error occurred. Please check your connection and try again.",
};

export const DEFAULT_FORM_DATA: FormData = {
  eventName: "",
  eventType: "",
  eventTypeOther: "",
  isScheduled: "",
  unscheduledNote: "",
  eventStartDate: "",
  eventEndDate: "",
  eventStartTime: "",
  eventEndTime: "",
  earliestSetupTime: "",
  requiredLeaveTime: "",
  locationDescription: "",
  addressLine1: "",
  addressLine2: "",
  city: "",
  state: "",
  zipCode: "",
  placeId: "",
  requestEctoVehicle: "no",
  ectoVehicleParkingInfo: "",
  maxEctoVehicles: "",
  memberParkingInfo: "",
  tablesProvided: "n/a",
  chairsProvided: "n/a",
  numberOfTables: "",
  numberOfChairs: "",
  charitableDonationsAllowed: "",
  needsLogistics: "",
  collectDonationsForHost: "",
  charityInfo: "",
  contactName: "",
  contactEmail: "",
  contactPhone: "",
  companyName: "",
  companyWebsite: "",
  additionalInfo: "",
};
